### ISSUE TITLE
Server Crash Bug on auth reload?

### ISSUE THREAD

**Issue by MatthewM** [Ichbinjoe/MCAuthenticator#2]
Looks like there's a bug in this that's causing Paper 1.9 to crash.

Judging by the fact that all I did on the server (no one else was on) is to /auth reload after changing a small thing I'd assume that this is likely to effect multiple people.

> [21:20:47 INFO]: Fayettemat issued server command: /auth
> [21:20:50 INFO]: Fayettemat issued server command: /auth enable
> [21:21:11 INFO]: Fayettemat issued server command: /auth reset
> [21:22:01 INFO]: [LogViewer] Fayettemat issued command: auth reload
> [LogServer] Command sent.
> [21:22:01 INFO]: [MCAuthenticator] Using RFC6238 (Google Authenticator 2FA) based > authentication.
> [21:23:03 ERROR]: The server has stopped responding!`

[Crash Dump Log](https://gist.github.com/MatthewM/257d3b292801073b8d93)

I'm going to try this again on another server in a few to see if it'll do it with just MCAuthenticator and the latest Paper 1.9. Also, I'm assuming this is due to the watch dog timer too.

I'll reply again once I do a bit more testing but I have 2FA and Yubikey both enabled and it's using a MySQL database as well.

**Comment by Ichbinjoe** [comment]
Yeah, for some reason the time check is taking wayyy to long. I'll add in a timeout.

**Comment by MatthewM** [comment]
Yeah, that's what I figured it would be as well. 

Also, can you add a time out for the /auth enable command? I think that'd be wise as people might type it and accidentally get locked into 2FA mode and not mean to.

**Comment by Ichbinjoe** [comment]
Those are 2 separate issues. Users **should** be able to do /auth disable if they want to not use 2FA, but I guess it was being stopped by authentication. I'll add that in as well.

**Comment by MatthewM** [comment]
Thanks for you attention to both of those matters. I'm pulling MCAuth from my server for now till it's fixed as I'm worried about a random crash. I'll be glad to test this once you've patched the time out for the time.

**Comment by Ichbinjoe** [comment]
The latest version is on the github, however, I am not going to push an update until tomorrow (in case something else comes in / 

I decide to write the catch for /auth disable). I will attach my latest version. I had to upload it as a zip because Github decided it didn't like me uploading .jars....
[MCAuthenticator.zip](https://github.com/Ichbinjoe/MCAuthenticator/files/162472/MCAuthenticator.zip)

**Comment by MatthewM** [comment]
Sounds good. I'll set up a test server ASAP. Depends on how busy work is tonight on when that is. I'll reply if I get it working or not when I know.
