### ISSUE TITLE
found auth error

### ISSUE THREAD

**Issue by DuckCraftPvP** [Ichbinjoe/MCAuthenticator#20]
Says my code from the authenticator app is invalid. 

Exact msg: That was not a valid code, You are not yet authenticated.

but it was a valid code. Tried 6 different codes.

**Comment by Ichbinjoe** [comment]
Post your startup log.

**Comment by DuckCraftPvP** [comment]
http://hastebin.com/igucepuham.md

Hope that helps.

**Comment by Ichbinjoe** [comment]
[00:21:39] [Server thread/ERROR]: [MCAuthenticator] Your server's Unix time is off by 10877 seconds! 2FA may not work! Please correct this to make sure 2FA works.

**Comment by DuckCraftPvP** [comment]
i fixed it also in the future, saying that would not help to fix it.

**Comment by Ichbinjoe** [comment]
It is in the logs: it is not my fault if you cannot read logs for your own server. Its not my job to parse your logs for something the plugin is telling you.

**Comment by DuckCraftPvP** [comment]
no i ment saying how to fix the unix time. i did not know till i googled 4 different sites to find out.
