### ISSUE TITLE
Feature to disable SSL for MySQL

### ISSUE THREAD

**Issue by ghost** [Ichbinjoe/MCAuthenticator#45]
MCAuthenticator is a great plugin when it comes to 2FA in Minecraft. However one simple feature should be added in the config, the possibility to disable SSL for the MySQL connection. 🙂

**Comment by CyberFlameGO** [comment]
Append `?useSSL=false` to the URI, e.g.:
```yaml
mysql:
    url: "jdbc:mysql://localhost:3306/db?useSSL=false”
```

**Comment by aaomidi** [comment]
Few things:

This project really hasn't been updated in a while. So uh, use at your own risk.

I should probably update it, but...Java.

And finally, please use secure comms layers when deploying this 😅
